### ISSUE TITLE
This validation will hurt the IP?

### ISSUE THREAD

**Issue by DavidFnck** [mailgun/flanker#124]
I know something like https://github.com/hbattat/verifyEmail can use PHP to validate the email.

but use it oftenly will cause the IP blocked, so the amount is limited.

I want to know Flanker will hurt the IP reputation or not?

Thank you

**Comment by horkhe** [comment]
Unlike the tool you mentioned Flanker does *not* make requests to MX servers to verify that such mailbox exists there. Therefore it cannot hurt your IP reputation. Flanker only checks the email address grammar, ESP specific grammar for a selected list of ESPs, and presence of MX records for the domain part of the email address.
