### ISSUE TITLE
Question about MAX_LINE_LENGTH in parsing.py

### ISSUE THREAD

**Issue by imgarylai** [mailgun/flanker#132]
Hello, 

Thanks for your working. I'm using this package to parse email but I meet a problem. 

The question is raised from https://github.com/mailgun/flanker/blob/8421b0eeea977b813f8edd39619a8c17d3cd41a7/flanker/mime/message/headers/parsing.py#L61-L65

Is the MAX_LINE_LENGTH necessary?

**Comment by horkhe** [comment]
In general I am all for limits, they help protect limited system resource and do no let operations run excessively long.

The value of this particular limit is a legacy that was introduced long time ago and nobody remembers why. It makes no sense. If anything it should be [998](https://tools.ietf.org/html/rfc5322#section-2.1.1). And we should probably updated it to be that way.

But why are you asking? Have you seen email headers longer than 10k in the wild?

**Comment by horkhe** [comment]
We decided to get rid of this limit after all. Fixed in #184.

**Comment by imgarylai** [comment]
Thanks for letting me know the issue is considered!
