### ISSUE TITLE
WebOb requirement for just MultiDict

### ISSUE THREAD

**Issue by syrusakbary** [mailgun/flanker#135]
At first, great work on this fantastic library!

I've been curious why this project needed `WebOb` and it seems it's just because of the `MultiDict`.
Given that `MultiDict` is just a small implementation in all the things that `WebOb` provide, could make sense to copy & paste the `MultiDict` implementation into this repo or use a [specific package for it](https://pypi.python.org/pypi/multidict)?

**Comment by punkrokk** [comment]
Why bother - they provide a function to getall and getitems for headers, saving you the work

**Comment by horkhe** [comment]
For historical reasons. Flanker used to be a part of a larger code base and inherited some of dependencies when it was extracted. I do not think that the specific package can be used as a drop in replacement. At least I personally encountered some incompatibility issues when I had tried to swap Multidict implementation in our code. So this seems like some work without any gain for us.

If somebody suggest a solution that allows nice way to plug in different Multidict implementations, then we are willing to consider it. So I am closing this as wontfix until such times.

**Comment by syrusakbary** [comment]
Makes sense! Thanks for taking time to review it :)
