### ISSUE TITLE
Upload releases to PyPI

### ISSUE THREAD

**Issue by dgouldin** [mailgun/flanker#172]
The latest release of flanker on PyPI is 0.4.38. Please upload the more recent releases so that they can be pip installed.

Thanks!

**Comment by horkhe** [comment]
The library goes through a lot of changes. We tag them for internal use, but are not comfortable enough with shipping them to the world.

**Comment by JocelynDelalande** [comment]
Go ahead :)

**Comment by horkhe** [comment]
v0.8.5 has been uploaded on PyPI

**Comment by JocelynDelalande** [comment]
Maxim Vladimirskiy <notifications@github.com> wrote:
> Closed #172.

That is great, thanks :-).

Jocelyn
