### ISSUE TITLE
Upload latest releases to PyPI (0.9.8)

### ISSUE THREAD

**Issue by christiankossmann** [mailgun/flanker#222]
Can you please upload the latest release to PyPI? Or are there any good reasons why the version on PyPI is still 0.9.0?

**Comment by bhrutledge** [comment]
I encountered #231, which seems to be fixed in 0.9.8. I see that the [latest GitHub release](https://github.com/mailgun/flanker/releases) is 0.9.10, but the [latest PyPI release](https://pypi.org/project/flanker/) is 0.9.0.

@thrawn01 and/or @horkhe, can you upload a new release to PyPI?

**Comment by HeroProtagonist** [comment]
I am also seeing #231 using the latest github release `flanker = { git = 'https://github.com/mailgun/flanker.git', ref = 'v0.9.10', editable = true }` and using python `3.6.0`

I forked the repo [here](https://github.com/HeroProtagonist/flanker/commit/dfba09110c856a70e8820fa5883bda643d551d75) and redid the parsetabs with `3.6.0` and I do not see the warnings  when using the fork. Also to note is when using python `2.7` and my fork I do not see the warnings. 
Wondering if I should PR my fork to get it into a release?

**Comment by zampettim** [comment]
I too need to get the latest release into PyPI. Any chance that will happen soon?

**Comment by horkhe** [comment]
Version v0.9.11 has been uploaded. Sorry for the delay.

**Comment by christiankossmann** [comment]
Thanks a lot!
