### ISSUE TITLE
Python 3 support?

### ISSUE THREAD

**Issue by thedrow** [mailgun/flanker#97]
The build is not running with Python 3.
Has anyone ever tried running the tests with Python 3? Is there a reason why it's not supported yet?

**Comment by ElvisTheKing** [comment]
Its 2015, would be nice to have python 3 support

**Comment by megha-n-bodke** [comment]
+1 for Python 3 support

**Comment by edwardotis** [comment]
+1

**Comment by sktzofrenic** [comment]
Umm yeah, another request for python 3 support.

**Comment by Evlos** [comment]
+1
```
└─[$] pip install flanker                                                                                                    [16:57:38]
Collecting flanker
  Downloading flanker-0.4.38.tar.gz (87kB)
    100% |████████████████████████████████| 90kB 97kB/s
Collecting chardet>=1.0.1 (from flanker)
  Downloading chardet-2.3.0.tar.gz (164kB)
    100% |████████████████████████████████| 167kB 95kB/s
Collecting cchardet>=0.3.5 (from flanker)
  Downloading cchardet-1.0.0.tar.gz (609kB)
    100% |████████████████████████████████| 610kB 853kB/s
Collecting cython>=0.21.1 (from flanker)
  Downloading Cython-0.23.4-cp35-cp35m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl (3.6MB)
    100% |████████████████████████████████| 3.6MB 126kB/s
Collecting dnsq>=1.1.6 (from flanker)
  Downloading dnsq-1.1.6.tar.gz
Collecting expiringdict>=1.1.2 (from flanker)
  Downloading expiringdict-1.1.3.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/sp/yghc86_51z55_7k6_n59s9600000gn/T/pip-build-muknokf8/expiringdict/setup.py", line 2, in <module>
        import md5  # fix for "No module named _md5" error
    ImportError: No module named 'md5'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/sp/yghc86_51z55_7k6_n59s9600000gn/T/pip-build-muknokf8/expiringdict
```

**Comment by sokser** [comment]
+1

**Comment by JonLevy** [comment]
+1

**Comment by dorellang** [comment]
+1

**Comment by jeffwidman** [comment]
Hey all--GitHub now supports [reactions](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments), so please use that to +1 the issue rather than spamming everyone following it with a text comment of "+1"

**Comment by adamrothman** [comment]
Seems like good progress has been made at https://github.com/plq/flanker – would bringing in some of their work be feasible?

**Comment by plq** [comment]
My work is mostly based on #106. I think you'd be better off with python3-specific stuff cherry-picked from https://github.com/BayanGroup/flanker/

**Comment by punkrokk** [comment]
Hey - it's getting crazy that py3 isn't supported yet.

**Comment by horkhe** [comment]
@punkrokk the bitter truth is that the Mailgun team does not have plans to add support for Python 3. But if somebody wants to contribute the support for Python 3 we are ready to consider it, as long as it does not break 2.7 functionality.

**Comment by alexei** [comment]
Hey, guys, for those of you looking for a Python 3 email parsing library I implemented [addresslib](https://github.com/alexei/python-addresslib). Unlike `flanker`, it doesn't implement its own parser. Instead it wraps Python's stdlib parser. There's also some Python 2 support. Cheers!

**Comment by punkrokk** [comment]
@alexei good stuff. If I had more time I’d help you and add mimeparsing to it.

**Comment by horkhe** [comment]
Actually the `addresslib` part of Flanker is already Python 3 compatible.
