### ISSUE TITLE
expiringdict: stale dependency?

### ISSUE THREAD

**Issue by leifurhauks** [mailgun/flanker#99]
Is `expiringdict` still required for this project? The github search bar only finds it in the `setup.py`. If it is no longer needed, it should be removed from the `setup.py`.

**Comment by leifurhauks** [comment]
on a related note, if the following from [User Manual.md](https://github.com/mailgun/flanker/blob/master/docs/User%20Manual.md#validating) is still correct, `dnsq` could stand to be changed to an optional dependency:

> By default, `flanker` uses the `dnsq` library (also written by Mailgun) to perform DNS
> lookups, however use of `dnsq` is not required. Any DNS lookup library can be used as
> long as it conforms to the same interface as that of a `dict`. See 
> [flanker/addresslib/drivers/dns_lookup.py](../flanker/addresslib/drivers/dns_lookup.py)
> for an example.

**Comment by edwardotis** [comment]
+1 this stale dependency is preventing installation of flanker on python 3.4

python --version
Python 3.4.3

$ pip install flanker
Collecting flanker
  Using cached flanker-0.4.37.tar.gz
Collecting chardet>=1.0.1 (from flanker)
Collecting cchardet>=0.3.5 (from flanker)
  Using cached cchardet-1.0.0.tar.gz
Collecting cython>=0.21.1 (from flanker)
  Using cached Cython-0.23.4.tar.gz
Collecting dnsq>=1.1.6 (from flanker)
  Using cached dnsq-1.1.6.tar.gz
Collecting expiringdict>=1.1.2 (from flanker)
  Using cached expiringdict-1.1.3.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-3_yfk8b6/expiringdict/setup.py", line 2, in <module>
        import md5  # fix for "No module named _md5" error
    ImportError: No module named 'md5'

**Comment by sokser** [comment]
+1

**Comment by horkhe** [comment]
Not an issue anymore
